### YamlMime:ManagedReference
items:
- uid: IO.Swagger.Models
  commentId: N:IO.Swagger.Models
  id: IO.Swagger.Models
  children:
  - IO.Swagger.Models.Customer
  - IO.Swagger.Models.Ticket
  - IO.Swagger.Models.Transaction
  langs:
  - csharp
  - vb
  name: IO.Swagger.Models
  nameWithType: IO.Swagger.Models
  fullName: IO.Swagger.Models
  type: Namespace
  assemblies:
  - IO.Swagger
references:
- uid: IO.Swagger.Models.Customer
  commentId: T:IO.Swagger.Models.Customer
  parent: IO.Swagger.Models
  isExternal: false
  name: Customer
  nameWithType: Customer
  fullName: IO.Swagger.Models.Customer
- uid: IO.Swagger.Models.Ticket
  commentId: T:IO.Swagger.Models.Ticket
  parent: IO.Swagger.Models
  isExternal: false
  name: Ticket
  nameWithType: Ticket
  fullName: IO.Swagger.Models.Ticket
- uid: IO.Swagger.Models.Transaction
  commentId: T:IO.Swagger.Models.Transaction
  parent: IO.Swagger.Models
  isExternal: false
  name: Transaction
  nameWithType: Transaction
  fullName: IO.Swagger.Models.Transaction
- uid: IO.Swagger.Models
  commentId: N:IO.Swagger.Models
  isExternal: false
  name: IO.Swagger.Models
  nameWithType: IO.Swagger.Models
  fullName: IO.Swagger.Models
