### YamlMime:ManagedReference
items:
- uid: IO.Swagger.Controllers
  commentId: N:IO.Swagger.Controllers
  id: IO.Swagger.Controllers
  children:
  - IO.Swagger.Controllers.EventApiController
  - IO.Swagger.Controllers.TicketApiController
  - IO.Swagger.Controllers.TransactionApiController
  - IO.Swagger.Controllers.UserApiController
  langs:
  - csharp
  - vb
  name: IO.Swagger.Controllers
  nameWithType: IO.Swagger.Controllers
  fullName: IO.Swagger.Controllers
  type: Namespace
  assemblies:
  - IO.Swagger
references:
- uid: IO.Swagger.Controllers.EventApiController
  commentId: T:IO.Swagger.Controllers.EventApiController
  isExternal: false
  name: EventApiController
  nameWithType: EventApiController
  fullName: IO.Swagger.Controllers.EventApiController
- uid: IO.Swagger.Controllers.TicketApiController
  commentId: T:IO.Swagger.Controllers.TicketApiController
  isExternal: false
  name: TicketApiController
  nameWithType: TicketApiController
  fullName: IO.Swagger.Controllers.TicketApiController
- uid: IO.Swagger.Controllers.TransactionApiController
  commentId: T:IO.Swagger.Controllers.TransactionApiController
  isExternal: false
  name: TransactionApiController
  nameWithType: TransactionApiController
  fullName: IO.Swagger.Controllers.TransactionApiController
- uid: IO.Swagger.Controllers.UserApiController
  commentId: T:IO.Swagger.Controllers.UserApiController
  isExternal: false
  name: UserApiController
  nameWithType: UserApiController
  fullName: IO.Swagger.Controllers.UserApiController
