### YamlMime:ManagedReference
items:
- uid: TicketApi.Settings
  commentId: N:TicketApi.Settings
  id: TicketApi.Settings
  children:
  - TicketApi.Settings.CustomSettings
  langs:
  - csharp
  - vb
  name: TicketApi.Settings
  nameWithType: TicketApi.Settings
  fullName: TicketApi.Settings
  type: Namespace
  assemblies:
  - TicketApi
references:
- uid: TicketApi.Settings.CustomSettings
  commentId: T:TicketApi.Settings.CustomSettings
  isExternal: false
  name: CustomSettings
  nameWithType: CustomSettings
  fullName: TicketApi.Settings.CustomSettings
